# Generated by Django 5.1 on 2024-10-29 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0003_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 21, 27, 44, 92752, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='testresult',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
