# Generated by Django 5.1 on 2024-10-30 22:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0004_testresult_created_testresult_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 22, 14, 12, 12807, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 10, 30, 22, 14, 12, 12807, tzinfo=datetime.timezone.utc))),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
