# Generated by Django 5.0.6 on 2024-11-05 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0005_alter_testresult_created_analysisresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 23, 1, 43, 135904, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 23, 1, 43, 135904, tzinfo=datetime.timezone.utc)),
        ),
    ]
