# Generated by Django 5.1.2 on 2024-11-06 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0011_alter_analysisresult_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='name',
            new_name='hospitalName',
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 3, 56, 2, 266355, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 3, 56, 2, 266355, tzinfo=datetime.timezone.utc)),
        ),
    ]
