# Generated by Django 5.1.2 on 2024-11-06 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0013_alter_analysisresult_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 9, 45, 20, 671589, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 9, 45, 20, 671589, tzinfo=datetime.timezone.utc)),
        ),
    ]
