# Generated by Django 5.1.2 on 2024-11-06 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0015_alter_analysisresult_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 10, 16, 29, 600171, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 10, 16, 29, 600171, tzinfo=datetime.timezone.utc)),
        ),
    ]
