# Generated by Django 5.1 on 2024-11-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0016_alter_analysisresult_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Hospital',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isDoctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
