# Generated by Django 5.1 on 2024-11-10 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0017_remove_user_hospital_remove_prescription_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientInformation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
