# Generated by Django 5.1 on 2024-11-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0019_propertyinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyinfo',
            old_name='images',
            new_name='image',
        ),
    ]
