# Generated by Django 5.1 on 2024-11-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0021_rename_price_propertyinfo_buy_propertyinfo_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinfo',
            name='image',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vaultapp.propertyinfo')),
            ],
        ),
    ]
