# Generated by Django 5.1 on 2024-11-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0022_remove_propertyinfo_image_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinfo',
            name='propertyType',
        ),
    ]
