# Generated by Django 5.1 on 2024-11-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0023_remove_propertyinfo_propertytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
